apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-config
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpc:
      port: {{ .Values.config.grpc.port | quote }}

    http:
      port: {{ .Values.config.http.port | quote }}

    log:
      level: {{ .Values.config.log.level | quote }}
