apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
      numExecutors: 4
      scmCheckoutRetryCount: 3
      mode: NORMAL
      labelString: "master"
      projectNamingStrategy: "standard"
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "admin"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      remotingSecurity:
        enabled: true
      securityOptions:
        - disableRememberMe: false
        - disableSignup: true
        - enableCaptcha: false
        - enableCSRF: true
        - enableXSS: true
        - preventCSRF: true
        - preventXSS: true
      globalNodeProperties:
        - envVars:
            env:
              - key: "DOCKER_REGISTRY"
                value: "your-registry.com"
              - key: "HELM_REPO"
                value: "https://charts.example.com"
              - key: "ARGOCD_SERVER"
                value: "argocd.example.com"
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default"
            namespace: "jenkins"
            jenkinsUrl: "http://jenkins:8080"
            jenkinsTunnel: "jenkins-agent:50000"
            containerCapStr: "10"
            maxRequestsPerHostStr: "32"
            templates:
              - name: "golang"
                label: "golang"
                nodeUsageMode: NORMAL
                containers:
                  - name: "golang"
                    image: "golang:1.21"
                    ttyEnabled: true
                    command: "cat"
                    resourceRequestCpu: "100m"
                    resourceRequestMemory: "128Mi"
                    resourceLimitCpu: "500m"
                    resourceLimitMemory: "512Mi"
              - name: "docker"
                label: "docker"
                nodeUsageMode: NORMAL
                containers:
                  - name: "docker"
                    image: "docker:latest"
                    ttyEnabled: true
                    command: "cat"
                    resourceRequestCpu: "100m"
                    resourceRequestMemory: "128Mi"
                    resourceLimitCpu: "500m"
                    resourceLimitMemory: "512Mi"
                    volumeMounts:
                      - mountPath: "/var/run/docker.sock"
                        name: "docker-sock"
                volumes:
                  - hostPathVolume:
                      hostPath: "/var/run/docker.sock"
                      name: "docker-sock"
      tools:
        git:
          installations:
            - name: "Default"
              home: "git"
        dockerTool:
          installations:
            - name: "docker"
              home: "/usr/bin/docker"
        helm:
          installations:
            - name: "helm"
              home: "/usr/local/bin/helm"
      plugins:
        required:
          - name: "kubernetes"
            version: "1.30.3"
          - name: "workflow-aggregator"
            version: "2.6"
          - name: "git"
            version: "4.7.2"
          - name: "configuration-as-code"
            version: "1.55"
          - name: "blueocean"
            version: "1.25.2"
          - name: "docker-workflow"
            version: "1.28"
          - name: "helm"
            version: "1.0.0"
          - name: "slack"
            version: "2.45"
          - name: "htmlpublisher"
            version: "1.25"
          - name: "gosec"
            version: "1.0.0"
