apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/khiem20tc/k8s-helm-linkerd-jenkins-argoCD.git
    targetRevision: HEAD
    path: k8s/helm/user-service
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: replicaCount
          value: "2"
        - name: ingress.enabled
          value: "true"
        - name: ingress.hosts[0].host
          value: "user-service-staging.local"
        - name: autoscaling.enabled
          value: "true"
        - name: autoscaling.minReplicas
          value: "2"
        - name: autoscaling.maxReplicas
          value: "5"
        - name: resources.limits.cpu
          value: "500m"
        - name: resources.limits.memory
          value: "512Mi"
        - name: resources.requests.cpu
          value: "100m"
        - name: resources.requests.memory
          value: "128Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: user-service-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
