#!/bin/bash

# Setup Infrastructure Script
# This script sets up the complete infrastructure for the GitOps workflow

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Always run from the repository root
cd "$(dirname "$0")/.."

# SAFETY: this is a test repo. Always use the local kind cluster from on-prem/
# (never the default ~/.kube/config) and refuse to talk to a non-local API server.
export KUBECONFIG="$PWD/on-prem/.kube/config"
guard_local_cluster() {
    [ -f "$KUBECONFIG" ] || { echo -e "${RED}❌ $KUBECONFIG not found. Run 'make -C on-prem up' first.${NC}"; exit 1; }
    local server
    server=$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')
    case "$server" in
        https://127.0.0.1:*|https://localhost:*) ;;
        *) echo -e "${RED}❌ Refusing to use non-local cluster: ${server}${NC}"; exit 1 ;;
    esac
}

# Configuration
DOCKER_REGISTRY=${DOCKER_REGISTRY:-"your-registry.com"}
NAMESPACE_PREFIX=${NAMESPACE_PREFIX:-"user-service"}

echo -e "${GREEN}🚀 Setting up GitOps Infrastructure${NC}"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to check prerequisites
check_prerequisites() {
    echo -e "${YELLOW}📋 Checking prerequisites...${NC}"
    
    local missing_tools=()
    
    if ! command_exists kubectl; then
        missing_tools+=("kubectl")
    fi
    
    if ! command_exists helm; then
        missing_tools+=("helm")
    fi
    
    if ! command_exists docker; then
        missing_tools+=("docker")
    fi

    if [ ${#missing_tools[@]} -ne 0 ]; then
        echo -e "${RED}❌ Missing required tools: ${missing_tools[*]}${NC}"
        echo "Please install the missing tools and try again."
        exit 1
    fi
    
    echo -e "${GREEN}✅ All prerequisites are installed${NC}"
}

# Function to setup Linkerd
setup_linkerd() {
    echo -e "${YELLOW}🔗 Setting up Linkerd service mesh...${NC}"
    
    # Install Linkerd CLI if not already installed
    if ! command_exists linkerd; then
        echo "Installing Linkerd CLI..."
        curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh
        export PATH=$PATH:$HOME/.linkerd2/bin
    fi
    
    # Validate the cluster before installing
    linkerd check --pre

    # Install Linkerd (idempotent: re-applying the manifests is safe)
    linkerd install --crds | kubectl apply -f -
    linkerd install | kubectl apply -f -

    # Wait for the control plane and verify the installation
    echo "Waiting for Linkerd to be ready..."
    linkerd check --wait 5m
    
    echo -e "${GREEN}✅ Linkerd installed successfully${NC}"
}

# Function to setup ArgoCD
setup_argocd() {
    echo -e "${YELLOW}🔄 Setting up ArgoCD...${NC}"
    
    # Create ArgoCD namespace
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
    
    # Install ArgoCD
    kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    
    # Wait for ArgoCD to be ready
    echo "Waiting for ArgoCD to be ready..."
    kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd
    
    echo -e "${GREEN}✅ ArgoCD installed successfully${NC}"
}

# Function to setup Jenkins
setup_jenkins() {
    echo -e "${YELLOW}🔧 Setting up Jenkins...${NC}"
    
    # Create Jenkins namespace
    kubectl create namespace jenkins --dry-run=client -o yaml | kubectl apply -f -
    
    # Add Jenkins Helm repository
    helm repo add jenkins https://charts.jenkins.io
    helm repo update
    
    # Install Jenkins (the chart generates a random admin password)
    helm upgrade --install jenkins jenkins/jenkins \
        --namespace jenkins \
        --values jenkins/values.yaml

    # Wait for Jenkins to be ready (the controller is a StatefulSet)
    echo "Waiting for Jenkins to be ready..."
    kubectl rollout status statefulset/jenkins -n jenkins --timeout=600s

    echo -e "${GREEN}✅ Jenkins installed successfully${NC}"
}

# Function to setup monitoring
setup_monitoring() {
    echo -e "${YELLOW}📊 Setting up monitoring...${NC}"
    
    # Install Prometheus and Grafana
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
    
    # Create monitoring namespace
    kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
    
    # Install Prometheus (Grafana admin password is generated by the chart)
    helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
        --namespace monitoring \
        --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false

    echo -e "${GREEN}✅ Monitoring stack installed successfully${NC}"
}

# Function to create namespaces
create_namespaces() {
    echo -e "${YELLOW}📁 Creating namespaces...${NC}"
    
    local environments=("dev" "staging" "prod")
    
    for env in "${environments[@]}"; do
        kubectl create namespace "${NAMESPACE_PREFIX}-${env}" --dry-run=client -o yaml | kubectl apply -f -
        
        # Add Linkerd injection label
        kubectl label namespace "${NAMESPACE_PREFIX}-${env}" linkerd.io/inject=enabled --overwrite
        
        echo -e "${GREEN}✅ Created namespace: ${NAMESPACE_PREFIX}-${env}${NC}"
    done
}

# Function to deploy ArgoCD applications
deploy_argocd_apps() {
    echo -e "${YELLOW}🚀 Deploying ArgoCD applications...${NC}"
    
    # Wait for ArgoCD to be ready
    kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd
    
    # The app-of-apps creates and manages everything in argocd/applications/
    kubectl apply -f argocd/app-of-apps.yaml
    
    echo -e "${GREEN}✅ ArgoCD applications deployed${NC}"
}

# Function to build and push Docker image
build_and_push_image() {
    echo -e "${YELLOW}🐳 Building and pushing Docker image...${NC}"
    
    # Build image
    docker build -t "${DOCKER_REGISTRY}/user-service:latest" app
    
    # Push image (if registry is configured)
    if [ "$DOCKER_REGISTRY" != "your-registry.com" ]; then
        docker push "${DOCKER_REGISTRY}/user-service:latest"
        echo -e "${GREEN}✅ Image pushed to registry${NC}"
    else
        echo -e "${YELLOW}⚠️  Skipping push - please configure DOCKER_REGISTRY${NC}"
    fi
}

# Main execution
main() {
    echo -e "${GREEN}🎯 Starting GitOps Infrastructure Setup${NC}"
    
    check_prerequisites
    guard_local_cluster
    setup_linkerd
    setup_argocd
    setup_jenkins
    setup_monitoring
    create_namespaces
    build_and_push_image
    deploy_argocd_apps
    
    echo -e "${GREEN}🎉 Infrastructure setup completed successfully!${NC}"
    echo ""
    echo -e "${YELLOW}📋 Access Information:${NC}"
    echo "ArgoCD:  make argocd-dashboard  -> https://localhost:8080  (user: admin)"
    echo "         password: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
    echo "Jenkins: make jenkins-dashboard -> http://localhost:8081   (user: admin)"
    echo "         password: kubectl -n jenkins get secret jenkins -o jsonpath='{.data.jenkins-admin-password}' | base64 -d"
    echo "Grafana: kubectl port-forward svc/prometheus-grafana -n monitoring 3000:80 -> http://localhost:3000 (user: admin)"
    echo "         password: kubectl -n monitoring get secret prometheus-grafana -o jsonpath='{.data.admin-password}' | base64 -d"
    echo ""
    echo -e "${YELLOW}🔧 Next Steps:${NC}"
    echo "1. Create the registry secret used by the Jenkins agents:"
    echo "   kubectl create secret docker-registry registry-credentials -n jenkins \\"
    echo "     --docker-server=<registry> --docker-username=<user> --docker-password=<token>"
    echo "2. Add Jenkins credentials 'git-credentials' (repo push access) and 'argocd-token'"
    echo "3. Set up Git webhooks for automatic builds"
    echo "4. Configure Slack notifications in Jenkins"
    echo "5. Test the deployment pipeline"
}

# Run main function
main "$@"
